#eureka:
#  instance:
#    hostname: ${copic-heroku-registry}.herokuapp.com
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaulZone: http://localhost:8761/eureka/
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: account-service
#          uri: lb://ACCOUNT-SERVICE
#          predicates:
#            - Path=/api/users/**
spring:
  application:
    name: gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 8081

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:password@localhost:8761}/eureka/


