
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI}
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/api/users/**
logging:
  level:
    org.springframework.cloud.gateway: TRACE


