#eureka:
#  instance:
#    hostname: ${copic-heroku-registry}.herokuapp.com
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaulZone: http://localhost:8761/eureka/
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: account-service
#          uri: lb://ACCOUNT-SERVICE
#          predicates:
#            - Path=/api/users/**
#spring:
#  application:
#    name: GATEWAY-SERVICE
#  cloud:
#    discovery:
#      enabled: true
#    gateway:
#      routes:
#        - id: account-service
#          uri: lb://ACCOUNT-SERVICE
#          predicates:
#            - Path=/api/users/**
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
#
#server:
#  port: 8080
#
#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    healthcheck:
#      enabled: true
#    serviceUrl:
#      defaultZone: ${EUREKA_URL:http://user:password@localhost:8761}/eureka/


server:
  port: ${PORT:8080}

eureka:
  instance:
    hostname: gateway.herokuapp.com
    homePageUrl: https://${eureka.instance.hostName}/
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:password@localhost:8761}/eureka/
spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/api/users/**
logging:
  level:
    org.springframework.cloud.gateway: TRACE


