
eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: security-service
          uri: lb://SECURITY-SERVICE
          predicates:
            - Path=/security/**
        - id: social-service
          uri: lb://SOCIAL-SERVICE
          predicates:
            - Path=/social/**
        - id: media-service
          uri: lb://MEDIA-SERVICE
          predicates:
            - Path=/media/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders:
              - id
              - content-type
              - Authorization
            allowedMethods:
              - GET
              - POST
              - PUT
logging:
  level:
    org.springframework.cloud.gateway: TRACE
server:
  port: ${PORT:8080}


